# Generated by Django 3.0.6 on 2020-05-08 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AppUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_role', models.IntegerField(choices=[(1, 'Normal User'), (2, 'Admin')], default=1)),
                ('user_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', djrichtextfield.models.RichTextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('commented_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commented_by', to='BugTracker.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('wiki', djrichtextfield.models.RichTextField()),
                ('status', models.IntegerField(choices=[(1, 'Under Development'), (2, 'Testing'), (3, 'Released')], default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator', to='BugTracker.AppUser')),
                ('members', models.ManyToManyField(blank=True, related_name='members_working', to='BugTracker.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Issues',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', djrichtextfield.models.RichTextField()),
                ('bug_status', models.IntegerField(choices=[(1, 'Pending'), (2, 'To be Discussed'), (3, 'Resolved')], default=1)),
                ('created_at', models.DateTimeField(editable=False)),
                ('tag', models.IntegerField(choices=[(1, 'Bug'), (2, 'Enhancement'), (3, 'UI/UX Improvement')], default=1)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_to', to='BugTracker.AppUser')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BugTracker.Project')),
                ('reported_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to='BugTracker.AppUser')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(blank=True, upload_to='')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BugTracker.Comment')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issue', to='BugTracker.Issues'),
        ),
    ]
