# Generated by Django 3.0.6 on 2020-05-09 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issues',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
