# Generated by Django 3.0.6 on 2020-05-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='enrNo',
            field=models.IntegerField(default=0),
        ),
    ]
