# Generated by Django 3.0.6 on 2020-05-14 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0002_appuser_enrno'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='access_token',
            field=models.CharField(default='', max_length=100),
        ),
    ]
