# Generated by Django 3.0.6 on 2020-05-14 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0003_appuser_access_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='access_token',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
