# Generated by Django 3.0.6 on 2020-05-18 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0004_auto_20200514_1206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
    ]
