# Generated by Django 3.0.7 on 2020-06-25 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0006_auto_20200522_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='appuser',
            name='is_disabled',
            field=models.BooleanField(default=0),
        ),
    ]
