# Generated by Django 3.0.7 on 2020-06-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0007_appuser_is_disabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appuser',
            name='display_picture',
            field=models.CharField(max_length=500),
        ),
    ]
