# Generated by Django 3.0.7 on 2020-06-28 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0008_auto_20200626_1606'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='comment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BugTracker.Issues'),
        ),
    ]
