# Generated by Django 3.0.7 on 2020-06-30 10:01

import BugTracker.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0011_auto_20200629_1311'),
    ]

    operations = [
        migrations.CreateModel(
            name='IssueImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=BugTracker.models.upload_path)),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BugTracker.Issues')),
            ],
        ),
    ]
