# Generated by Django 3.0.7 on 2020-06-30 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0012_issueimages'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
