# Generated by Django 3.0.7 on 2020-07-01 07:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0014_remove_issues_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tagName', models.CharField(max_length=50)),
                ('icon', models.CharField(default='tag', max_length=50)),
                ('color', models.IntegerField(choices=[(1, 'red'), (2, 'orange'), (3, 'yellow'), (4, 'olive'), (5, 'green'), (6, 'teal'), (7, 'blue'), (8, 'violet'), (9, 'purple'), (10, 'pink'), (11, 'brown'), (12, 'grey'), (13, 'black')], default=1)),
            ],
        ),
        migrations.AlterField(
            model_name='issues',
            name='reported_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reported_by', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='issues',
            name='tags',
            field=models.ManyToManyField(related_name='tags', to='BugTracker.Tags'),
        ),
    ]
