# Generated by Django 3.0.7 on 2020-07-03 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BugTracker', '0015_auto_20200701_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tags',
            name='tagName',
            field=models.CharField(default='Bug', max_length=50),
        ),
    ]
