// Type of actions in the 

export const FETCH_USER_PROFILE_SUCCESS = 'FETCH_USER_PROFILE_SUCCESS'
export const FETCH_USER_PROFILE_FAILURE = 'FETCH_USER_PROFILE_FAILURE'
export const FETCH_PROJECT_DETAILS_SUCCESS = 'FETCH_PROJECT_DETAILS_SUCCESS'
export const FETCH_PROJECT_DETAILS_FAILURE = 'FETCH_PROJECT_DETAILS_FAILURE'
export const FETCH_ISSUES_DETAILS_SUCCESS = 'FETCH_ISSUES_DETAILS_SUCCESS'
export const FETCH_ISSUES_DETAILS_FAILURE = 'FETCH_ISSUES_DETAILS_FAILURE'
export const FETCH_COMMENT_DETAILS_SUCCESS = 'FETCH_COMMENT_DETAILS_SUCCESS'
export const FETCH_COMMENT_DETAILS_FAILURE = 'FETCH_COMMENT_DETAILS_FAILURE'
export const FETCH_CURRENT_USER_PROFILE_SUCCESS = 'FETCH_CURRENT_USER_PROFILE_SUCCESS'
export const FETCH_CURRENT_USER_PROFILE_FAILURE = 'FETCH_CURRENT_USER_PROFILE_FAILURE'
